name: xpert_funding_test
description: "A flutter project for clean architecture"
publish_to: 'none'

# The following de es the version and build number for your application. # A version number is three numbers separated by dots, like 1.2.4 # followed by an optional build number separated by a +. # Both the version and the builder number may be overridden in flutter # build by specifying --build-name and --build-number, respectively. # In Android, build-name is used as versionName while build-number used as versionCode. # Read more about Android versioning at https://developer.android.com/studio/publish/versioning # In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion. # Read more about iOS versioning at # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html # In Windows, build-name is used as the major, minor, and patch parts # of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.6.0
  equatable: ^2.0.7
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_pin_code_fields: ^2.2.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.20.2
  json_annotation: any
  local_auth: ^2.3.0
  lottie: ^3.1.2
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  phone_form_field: ^10.0.3
  pin_code_fields: ^8.0.1
  printing: ^5.13.4
  retrofit: any
  share_plus: ^10.1.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.0
dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  retrofit_generator: ^8.0.5

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/animations/
    - assets/audio/
    - assets/json/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Mona
      fonts:
        # - asset: assets/fonts/
        - asset: assets/fonts/mona-sans-bold.ttf
        - asset: assets/fonts/mona-sans-light.ttf
        - asset: assets/fonts/mona-sans-medium.ttf
        - asset: assets/fonts/mona-sans-regular.ttf
        - asset: assets/fonts/mona-sans.ttf
